version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: chambal-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chambal_local
      MYSQL_USER: chambal_user
      MYSQL_PASSWORD: chambal_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
